// Stub build_options module for Ch08 examples
// In a real build, this would be generated by the build system

pub const version = "1.0.0";
pub const max_connections: u32 = 100;
pub const enable_logging = true;
