#!/bin/bash
# Proofreading Check Script for Zig Developer Guide
# Checks for common consistency issues across all chapters

SECTIONS_DIR="/home/user/zig_guide/sections"
REPORT_FILE="/home/user/zig_guide/proofreading_report.md"

echo "# Proofreading Report - $(date +%Y-%m-%d)" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Generated by: scripts/proofread_check.sh" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Check for broken footnote references
echo "## 1. Footnote Reference Checks" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for chapter_dir in "$SECTIONS_DIR"/*/; do
    chapter_name=$(basename "$chapter_dir")
    content_file="${chapter_dir}content.md"

    if [ -f "$content_file" ]; then
        echo "### $chapter_name" >> "$REPORT_FILE"

        # Extract all footnote references [^N]
        refs=$(grep -o "\[\^[0-9]\+\]" "$content_file" | sort | uniq)

        # Extract all footnote definitions [^N]:
        defs=$(grep -o "^\[\^[0-9]\+\]:" "$content_file" | sed 's/:$//' | sort | uniq)

        # Count them
        ref_count=$(echo "$refs" | grep -c "\[\^" || echo "0")
        def_count=$(echo "$defs" | grep -c "\[\^" || echo "0")

        echo "- Footnote references: $ref_count" >> "$REPORT_FILE"
        echo "- Footnote definitions: $def_count" >> "$REPORT_FILE"

        # Check for missing definitions
        if [ "$ref_count" -gt 0 ]; then
            echo "$refs" | while read -r ref; do
                if [ -n "$ref" ]; then
                    def_pattern="^${ref}:"
                    if ! grep -q "$def_pattern" "$content_file"; then
                        echo "  - ⚠️  Missing definition for $ref" >> "$REPORT_FILE"
                    fi
                fi
            done
        fi

        # Check for unused definitions
        if [ "$def_count" -gt 0 ]; then
            echo "$defs" | while read -r def; do
                if [ -n "$def" ]; then
                    if ! grep -q "$def" "$content_file" | grep -v "^\\["; then
                        # This is hard to check accurately with grep, skip for now
                        :
                    fi
                fi
            done
        fi

        echo "" >> "$REPORT_FILE"
    fi
done

# Check for cross-chapter references
echo "## 2. Cross-Chapter Reference Checks" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for chapter_dir in "$SECTIONS_DIR"/*/; do
    chapter_name=$(basename "$chapter_dir")
    content_file="${chapter_dir}content.md"

    if [ -f "$content_file" ]; then
        refs=$(grep -n "Chapter [0-9]" "$content_file" || true)
        if [ -n "$refs" ]; then
            echo "### $chapter_name" >> "$REPORT_FILE"
            echo '```' >> "$REPORT_FILE"
            echo "$refs" >> "$REPORT_FILE"
            echo '```' >> "$REPORT_FILE"
            echo "" >> "$REPORT_FILE"
        fi
    fi
done

# Check for common typos and issues
echo "## 3. Common Issues" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for chapter_dir in "$SECTIONS_DIR"/*/; do
    chapter_name=$(basename "$chapter_dir")
    content_file="${chapter_dir}content.md"

    if [ -f "$content_file" ]; then
        issues=""

        # Check for double spaces
        double_spaces=$(grep -n "  " "$content_file" | grep -v "^    " | grep -v "^  -" | head -5 || true)
        if [ -n "$double_spaces" ]; then
            issues="${issues}\n- Double spaces found"
        fi

        # Check for TODO/FIXME/XXX
        todos=$(grep -ni "TODO\|FIXME\|XXX" "$content_file" || true)
        if [ -n "$todos" ]; then
            issues="${issues}\n- TODO/FIXME markers found:\n\`\`\`\n${todos}\n\`\`\`"
        fi

        if [ -n "$issues" ]; then
            echo "### $chapter_name" >> "$REPORT_FILE"
            echo -e "$issues" >> "$REPORT_FILE"
            echo "" >> "$REPORT_FILE"
        fi
    fi
done

echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Report complete. Review $REPORT_FILE for details." >> "$REPORT_FILE"

cat "$REPORT_FILE"
